DailyFrsh/DailyFrsh/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),  # 站点管理
    url(r'^user/', include('apps.user.urls', namespace='user')), # 用户模块
    url(r'^cart/', include('apps.cart.urls', namespace='cart')), # 购物车模块
    url(r'^order/', include('apps.order.urls', namespace='order')), # 订单模块
    url(r'^', include('apps.goods.urls', namespace='goods')), # 商品模块
]

DailyFrsh/apps/cart/urls.py
from django.conf.urls import url
from apps.cart.views import CartInfoView, CartAddView, CartUpdateView, CartDeleteView

urlpatterns = [
    url(r'^$', CartInfoView.as_view(), name='show'),  # 购物车首页
    url(r'^add$', CartAddView.as_view(), name='add'),  # 添加购物车
    url(r'^update$', CartUpdateView.as_view(), name='update'),  # 购物车页面的操作， 数量增加/减少，删除等
    url(r'^delete$', CartDeleteView.as_view(), name='delete'),  # 删除购物车内商品





]

DailyFrsh/apps/goods/urls.py
from django.conf.urls import url
from apps.goods.views import IndexView, DetailView, ListView


urlpatterns = [
    url(r'^index$', IndexView.as_view(), name='index'),  # 首页
    url(r'^goods/(?P<sku_id>\d+)$', DetailView.as_view(), name='detail'),  # 商品详情页
    url(r'^list/(?P<type_id>\d+)/(?P<page>\d+)$', ListView.as_view(), name='list'), # 每个种类的商品的列表



]

DailyFrsh/apps/user/urls.py
from django.conf.urls import url
from apps.user.views import register, RegisterView, ActiveView, LoginView, LogoutView, UserinfoView, UseraddressView, UserorderView

urlpatterns = [
    # url(r'^register$', register),
    url(r'^register$', RegisterView.as_view(), name='register'),  # 类视图的方法, 反向解析
    url(r'^active/(?P<token>.*)$', ActiveView.as_view(), name='active'),  # 激活 用户信息
    url(r'^login$', LoginView.as_view(), name='login'),  # 用户登陆

    url(r'^logout$', LogoutView.as_view(), name='logout'),  # 用户退出

    url(r'^$', UserinfoView.as_view(), name='user'),  # 用户中心
    url(r'^address$', UseraddressView.as_view(), name='address'),  # 用户地址
    url(r'^order/(?P<page>\d+)$', UserorderView.as_view(), name='order'),  # 用户订单
]

DailyFrsh/apps/cart/models.py
from django.db import models

# Create your models here.

DailyFrsh/apps/cart/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.core.urlresolvers import reverse
from utils.mixin import LoginRequiredMixin

from django.views.generic import View
from django_redis import get_redis_connection
from apps.goods.models import GoodsSKU

# Create your views here.
# 购物车: 跳转到购物车页面; 添加购物车
# 1 跳转购物车页面 页面需要用户先登陆才能跳转 /cart/
# 自动跳转登录页面， loginrequired() 这个函数做了
class CartInfoView(LoginRequiredMixin, View):
    def get(self, request):
        # 显示购物车页面
        # 获取登陆用户
        user = request.user
        # 从redis中获取用户购物车记录信息   cart_id {sku_id:num, sku_id:num, ...}
        con = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id
        cart_dict = con.hgetall(cart_key)  # hgetall得到的是字典{sku_id:num, skku_id:num, ...}, 保存有商品id和数量

        skus = []  # 购物车的商品组成的列表
        total_count = 0  # 假设初始总数量为0
        total_price = 0  # 初始价格为0
        # cart_dict.items() 方法 得到的是字典的键值对组成的元组,元组组成的列表; 如果用两个变量接收, 就可以得到对应的键和值
        for sku_id, count in cart_dict.items():
            # 根据商品id获取商品信息
            sku = GoodsSKU.objects.get(id=sku_id)
            # 计算商品的小计  数量*单价
            amount = sku.price * int(count)
            # 动态给sku增加属性 count 和 amount, 分别保存购物车的商品数量和商品的小计
            sku.count = count
            sku.amount = amount

            # 追加sku
            skus.append(sku)

            # 累计叠加商品的数量和商品的价格
            total_count += int(count)
            total_price += amount

            # 上下文,模板和后台传递参数
        context = {
            'total_count': total_count,
            'total_price': total_price,
            'skus': skus
        }

        return render(request, 'cart.html', context)


# get 从服务器获取数据 //  post 涉及到数据库的修改(增加,修改, 删除)  --> 这里用post
# ajax请求操作,局部刷新, 只有购物车刷新,不是全部页面的刷新,
# ajax请求, 后台返回的是json数据
# 传递的参数: 商品的id(sku_id), 商品的数量(count)
# 匹配路径 /cart/add
class CartAddView(View):
    # 添加购物车
    def post(self, request):
        # 获取用户:
        user = request.user
        if not user.is_authenticated():
            # 用户未登录
            return JsonResponse({'res': 0, 'errmsg': '请先登陆'})
        # else:  表示用户已经登陆, 省略了, 注意缩进
        # 接收参数: 用户提交的收藏数据: sku_id, count
        sku_id= request.POST.get('sku_id')
        count = request.POST.get('count')

        # 校验接收到的参数
        if not all([sku_id, count]):
            return JsonResponse({'res': 1, 'errmsg': '数据不完整'})
        # 数据完整了,要校验商品的id  sku_id
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'res': 2, 'errmsg': '商品不存在'})
        # 校验数量:
        try:
            count = int(count)
        except Exception as e:
            return JsonResponse({'res': 3, 'errmsg': '商品数量不正确'})
        # else:
        if count <= 0:
            return JsonResponse({'res': 3, 'errmsg': '商品数量不正确'})

        # 都正确了，下面开始处理业务逻辑
        # sku_id 已经存在的商品，对商品的数量进行那个增加， 如果不存在，就新增加商品的sku_id
        con = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id
        # 取出sku_id的值， hget()方法，
        cart_count = con.hget(cart_key, sku_id)
        # 如果能通过sku_id 取到cart_count, 就表示该商品已经加入购物车了
        if cart_count:
            count += int(cart_count)
        # 已经加入购物车的商品再次添加时进行该商品数量上的添加， 要判断库存
        #判断库存
        if count > sku.stock:
            return JsonResponse({'res': 4, 'errmsg': '该商品库存不足'})

        # 设置sku_id 对应的值
        con.hset(cart_key, sku_id, count)
        # 获取购物车中商品的条目数
        cart_count = con.hlen(cart_key)

        # 返回应答 json数据
        return JsonResponse({'res': 5, 'cart_count': cart_count, 'msg': '添加成功'})


# 在购物车页面进行的操作， 增加/减少，修改，删除
# 一部分不设计前后段交互的操作，可以直接前段jQ操作， 前面的勾选商品，是否全选， 后面的商品数量的增加减少， 都不涉及后端交互
# 设计前后段交互的要使用ajax请求  局部刷新    涉及后端交互的操作： 后面的删除，

class CartUpdateView(View):
    # 涉及到数据库的操作，post请求
    def post(self, request):
        user = request.user
        if not user.is_authenticated():
            return JsonResponse({'res': 0, 'errmsg': '请先登陆'})

        # 接收参数
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')
        # 对接收到的参数进行校验： 完整性， 有效性
        if not all([sku_id, count]):
            return JsonResponse({'res': 1, 'errmsg': '数据不完整'})
        # 校验商品的id
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'res': 2, 'errmsg': '商品不存在'})
        # 校验商品的数目
        try:
            count = int(count)
        except Exception as e:
            return JsonResponse({'res': 3, 'errmsg': '商品数量不合法'})
        if count < 0:
            return JsonResponse({'res': 3, 'errmsg': '商品数量不合法'})

        # 业务处理， 更新购物车记录
        con = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id

        # 判断库存
        if count > sku.stock:
            return JsonResponse({'res': 4, 'errmsg': '商品库存不足'})

        # 更新redis数据库中的商品的数量
        con.hset(cart_key, sku_id, count)

        # 计算购物车中商品的总件数
        total_count = 0
        vals = con.hvals(cart_key, sku_id)
        for val in vals:
            total_count += int(val)

        return JsonResponse({'res': 5, 'total_count': total_count, 'msg': '更新成功'})

# 删除用户购物车商品
# 需要传递的参数： 商品的id
class CartDeleteView(View):
    # 删除购物车
    def post(self, request):
        user = request.user
        if not user.is_authenticated():
            return JsonResponse({'res': 0, 'errmsg': '请先登陆'})
        sku_id = request.POST.get('sku_id')
        if not sku_id:
            return JsonResponse({'res': 1, 'errmsg': '数据不完整'})
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except Exception as e:
            return JsonResponse({'res': 2, 'errmsg': '商品不存在'})

        # 处理业务
        con = get_redis_connection('default')
        cart_key = "cart_%d" % user.id

        # 通过商品id删除信息
        con.hdel(cart_key, sku_id)

        # 计算用户购物车中商品的总数
        total_count = 0
        vals = con.hvals(cart_key)
        for val in vals:
            total_count += int(val)

        return JsonResponse({'res': 3, 'total_count': total_count, 'msg': '删除成功'})

DailyFrsh/templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
    {% load staticfiles %}
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>{% block title %}{% endblock title %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">

	{% block topfiles %}{% endblock topfiles %}
</head>
<body>
{% block header_con %}
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
                {% if user.is_authenticated %}
                {#  is_authenticated() 方法是判断用户是否登陆,django 封装好的, #}
                    <div class="login_btn fl">
                        欢迎您：<em>{{ user.username }}</em>
                        <span>|</span>
                        <a href="{% url 'user:logout' %}">退出</a>
                    </div>
                {% else %}
                    <div class="login_btn fl">
                        <a href="{% url 'user:login' %}">登录</a>
                        <span>|</span>
                        <a href="{% url 'user:register' %}">注册</a>
                    </div>
                {% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'user:user' %}">用户中心</a>
					<span>|</span>
					<a href="{% url 'cart:show' %}">我的购物车</a>
					<span>|</span>
					<a href="{% url 'user:order' 1 %}">我的订单</a>
				</div>
			</div>
		</div>		
	</div>
{% endblock header_con %}

{% block search_bar %}
	<div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="search_con fl">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
            {% if user.is_authenticated %}
            <div class="guest_cart fr">
                <a href="{% url "cart:show" %}" class="cart_name fl">我的购物车</a>
                <div class="goods_count fl" id="show_count">{{ cart_count }}</div>
            </div>
            {% endif %}
	</div>
{% endblock search_bar %}

{% block body %}
{% endblock body %}

	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	{% block bottom %}{% endblock bottom %}
    {% block bottomfiles %}{% endblock bottomfiles %}
</body>
</html>

DailyFrsh/templates/base_no_cart.html
{% extends 'base.html' %}
{% load staticfiles %}
{# 网页搜索框块 #}
{% block search_bar %}
	<div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;{% block page_title %}{% endblock page_title %}</div>
		<div class="search_con fr">
            <form method="get" action="/search">
			<input type="text" class="input_text fl" name="q" placeholder="搜索商品">
			<input type="submit" class="input_btn fr" name="" value="搜索">
            </form>
		</div>
	</div>
{% endblock search_bar %}

DailyFrsh/templates/base_user_center.html
{% extends 'base_no_cart.html' %}
{#{% load staticfiles %}#}
{% block title %}天天生鲜-用户中心{% endblock title %}
{% block page_title %}用户中心{% endblock page_title %}
{% block body %}
    <div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'user:user' %}" {% if page == 'user' %}class="active"{% endif %}>· 个人信息</a></li>
				<li><a href="{% url 'user:order' 1 %}" {% if page == 'order' %}class="active"{% endif %}>· 全部订单</a></li>
				<li><a href="{% url 'user:address' %}" {% if page == 'address' %}class="active"{% endif %}>· 收货地址</a></li>
			</ul>
		</div>
        {# 用户中心-右侧内容块 #}
		{% block right_content %}{% endblock right_content %}
	</div>
{% endblock body %}

DailyFrsh/templates/detail.html
{% extends 'base_detail_list.html' %}
{% load staticfiles %}
{% block title %}天天生鲜-商品详情{% endblock title %}
{% block main_content %}
	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">{{ sku.type.name }}</a>
		<span>></span>
		<a href="#">商品详情</a>
	</div>

	<div class="goods_detail_con clearfix">
		<div class="goods_detail_pic fl"><img src="{{ sku.image.url }}"></div>

		<div class="goods_detail_list fr">
			<h3>{{ sku.name }}</h3>
			<p>{{ sku.desc }}</p>
			<div class="prize_bar">
				<span class="show_pirze">¥<em>{{ sku.price }}</em></span>
				<span class="show_unit">单  位：{{ sku.unite }}</span>
			</div>
			<div class="goods_num clearfix">
				<div class="num_name fl">数 量：</div>
				<div class="num_add fl">
					<input type="text" class="num_show fl" value="1">
					<a href="javascript:;" class="add fr">+</a>
					<a href="javascript:;" class="minus fr">-</a>
				</div>
			</div>
            <div>
                <div>其他规格:</div>
                <div>
                    {% for sku in same_spu_skus %}
                        <a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a>
                    {% endfor %}
                </div>
            </div>
			<div class="total">总价：<em>{{ sku.price }}元</em></div>
			<div class="operate_btn">
                {% csrf_token %}
				<a href="javascript:;" class="buy_btn">立即购买</a>
				<a href="javascript:;" class="add_cart" sku_id="{{ sku.id }}" id="add_cart">加入购物车</a>
			</div>
		</div>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
                    {% for sku in new_skus %}
					<li>
						<a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.image.url }}"></a>
						<h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
						<div class="prize">￥{{ sku.price }}</div>
					</li>
                    {% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<ul class="detail_tab clearfix">
				<li class="active">商品介绍</li>
				<li>评论</li>
			</ul>

			<div class="tab_content">
				<dl>
					<dt>商品详情：</dt>
					<dd>{{ sku.goods.detail|safe }}</dd>
				</dl>
			</div>

            <div class="tab_content" style="display: none;">
				<dl>
                    {% for order_sku in order_skus %}
                        <dt>评论时间: {{ order_sku.update_time }} 用户名:{{ order_sku.order.user.username }}</dt>
                        <dd>评论内容: {{ order_sku.comment }}</dd>
                    {% empty %}
                        暂时没有评论信息
                    {% endfor %}
				</dl>
			</div>

		</div>
	</div>
{% endblock main_content %}
{% block bottom %}
	<div class="add_jump"></div>
{% endblock bottom %}
{% block bottomfiles %}
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript">
        // 计算商品的小计
        function update_sku_amount() {
            count = $('.num_show').val();
            price = $('.show_pirze').children('em').text();
            // 计算小计
            count = parseInt(count);
            price = parseFloat(price);
            amount = count * price;
            // 设置商品的小计
            $('.total').children('em').text(amount.toFixed(2)+'元')
        }

        // 商品数量的增加， 按钮点击操作
        $('.add').click(function () {
            // 获取商品的数量
            count = $('.num_show').val();
            // 点击按钮增加1
            count = parseInt(count) + 1;
            // 重新设置商品数目
            $('.num_show').val(count);
            // 更新商品小计，  计算出商品现在数量下的价格
            update_sku_amount()
        });


        // 商品数目的减少， 按钮点击操作
         $('.minus').click(function () {
            // 获取商品的数量
            count = $('.num_show').val();
            // 点击按钮减少1
            count = parseInt(count) - 1;
            // 如果减少到0以下， count应该置为1
            if(count<=0){
                count = 1
            }
            // 重新设置商品数目
            $('.num_show').val(count);
            // 更新商品小计，  计算出商品现在数量下的价格
            update_sku_amount()
        });


         // 手动输入数字
        // 当输入框  失去焦点时  判断
         $('.num_show').blur(function () {
            // 获取商品的数量
            count = $(this).val();
            // 判断输入是否合法, isNaN 是否为数字， trim 去除空格，判断去除空格之后是否为0， 转为整数之后是否小于等于0
             if(isNaN(count) || count.trim().length == 0 || parseInt(count)<=0){
                 count = 1;
                 // 输入不合法，count置为1
             }
            // 重新设置商品数目
            $('.num_show').val(count);
            // 更新商品小计，  计算出商品现在数量下的价格
            update_sku_amount()
        });


         // 获取add_cart a标签左上角的坐标
		var $add_x = $('#add_cart').offset().top;
		var $add_y = $('#add_cart').offset().left;

        // 获取show_count div元素左上角的坐标
		var $to_x = $('#show_count').offset().top;
		var $to_y = $('#show_count').offset().left;

        // 加入购物车的操作处理
        // 处理ajax请求，
        $('#add_cart').click(function () {
            // 获取商品的id和条目数
            var count = $('.num_show').val();
            var sku_id = $(this).attr('sku_id');  // 获取属性有两种方法， prop(),,  attr()  有区别，百度
            // post 请求， 要求验证， jq的验证和html的验证有点区别
            var csrf = $('input[name="csrfmiddlewaretoken"]').val();
            // 组织参数
            var params = {'sku_id': sku_id, 'count': count, 'csrfmiddlewaretoken': csrf};

            // 发送ajax请求
            $.post('/cart/add', params, function (data) {
                if(data.res == 5){
                    // 添加成功
                    $(".add_jump").css({'left':$add_y+80,'top':$add_x+10,'display':'block'});

                        $(".add_jump").stop().animate({
                        'left': $to_y+7,
                        'top': $to_x+7},
                        "fast", function() {
                            $(".add_jump").fadeOut('fast',function(){
                                // 重新设置用户购物车中商品的条目数
                                $('#show_count').html(data.cart_count);
                            });
                        });
                        alert(data.msg)
                }
                else{
                    {# alert(status);#}
                    alert(data.errmsg)
                }
            })
        })

	</script>
{% endblock bottomfiles %}

DailyFrsh/templates/list.html
{% extends 'base_detail_list.html' %}
{% block title %}天天生鲜-商品列表{% endblock title %}
{% block main_content %}
	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">{{ type.name }}</a>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
                    {% for sku in new_skus %}
					<li>
						<a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.image.url }}"></a>
						<h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
						<div class="prize">￥{{ sku.price }}</div>
					</li>
                    {% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<div class="sort_bar">
				<a href="{% url 'goods:list' type.id 1 %}" {% if sort == 'default' %}class="active"{% endif %}>默认</a>
				<a href="{% url 'goods:list' type.id 1 %}?sort=price" {% if sort == 'price' %}class="active"{% endif %}>价格</a>
				<a href="{% url 'goods:list' type.id 1 %}?sort=hot" {% if sort == 'hot' %}class="active"{% endif %}>人气</a>
			</div>

			<ul class="goods_type_list clearfix">
                {# {% for sku in skus_page.object_list %} #}
                {% for sku in skus_page %}
				<li>
					<a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.image.url }}"></a>
					<h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
					<div class="operate">
						<span class="prize">￥{{ sku.price }}</span>
						<span class="unit">{{ sku.price }}/{{ sku.unite }}</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
                {% endfor %}
			</ul>

			<div class="pagenation">
                {% if skus_page.has_previous %}
				<a href="{% url 'goods:list' type.id skus_page.previous_page_number %}?sort={{ sort }}"><上一页</a>
                {% endif %}
                {% for pindex in skus_page.paginator.page_range %}
                    {% if pindex == skus_page.number %}
				    <a href="{% url 'goods:list' type.id pindex %}?sort={{ sort }}" class="active">{{ pindex }}</a>
                    {% else %}
				    <a href="{% url 'goods:list' type.id pindex %}?sort={{ sort }}">{{ pindex }}</a>
                    {% endif %}
				{% endfor %}
                {% if skus_page.has_next %}
				<a href="{% url 'goods:list' type.id skus_page.next_page_number %}?sort={{ sort }}">下一页></a>
                {% endif %}
			</div>
		</div>
	</div>
{% endblock main_content %}

DailyFrsh/templates/static_base.html
{# 登录 注册 首页 #}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{% load staticfiles %}
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    {# 网页标题块 #}
	<title>{% block title %}{% endblock title %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    {# 网页顶部引入文件块 #}
	{% block topfiles %}{% endblock topfiles %}
</head>
<body>

{# 网页顶部欢迎信息块 #}
{% block header_con %}
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				<div class="login_btn fl">
					<a href="{% url 'user:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'user:register' %}">注册</a>
				</div>
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'user:user' %}">用户中心</a>
					<span>|</span>
					<a href="{% url 'cart:show' %}">我的购物车</a>
					<span>|</span>
					<a href="{% url 'user:order' %}">我的订单</a>
				</div>
			</div>
		</div>
	</div>
{% endblock header_con %}

{# 网页搜索框块 #}
{% block search_bar %}
	<div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="search_con fl">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
		<div class="guest_cart fr">
			<a href="{% url 'cart:show' %}" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">{{ cart_count }}</div>
		</div>
	</div>
{% endblock search_bar %}

{# 网页主体内容块 #}
{% block body %}{% endblock body %}

	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
    {# 网页底部html元素块 #}
    {% block bottom %}{% endblock bottom %}
    {# 网页底部引入文件块 #}
	{% block bottomfiles %}{% endblock bottomfiles %}
</body>
</html>

DailyFrsh/templates/user_center_info.html
{% extends 'base_user_center.html' %}
{% block right_content %}
		<div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">
							<li><span>用户名：</span>{{ user.username }}</li>
                            {% if address %}
                                <li><span>联系方式：</span>{{ address.phone }}</li>
                                <li><span>联系地址：</span>{{ address.addr }}</li>
                            {% else %}
                                <li><span>联系方式：</span>无</li>
							    <li><span>联系地址：</span>无</li>
                            {% endif %}
						</ul>
				</div>

				<h3 class="common_title2">最近浏览</h3>
				<div class="has_view_list">
					<ul class="goods_type_list clearfix">
                        {% for sku in skus %}
				        <li>
                            <a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.image.url }}"></a>
                            <h4><a href="detail.html">{{ sku.name }}</a></h4>
                            <div class="operate">
                                <span class="prize">￥{{ sku.price }}</span>
                                <span class="unit">{{ sku.price }}/{{ sku.unite }}</span>
                                <a href="#" class="add_goods" title="加入购物车"></a>
                            </div>
                        </li>
                        {% empty %}
                            没有浏览记录
                        {% endfor %}
			        </ul>
		        </div>
		</div>
{% endblock right_content %}